import random


class LifeLinkManager:
    def __init__(self):
        self.links = ["https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life", "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life",
                      "https://www.wellnessblossom.life/2025/06/what-to-eat-for-a-healthier-skin.html",
                      "https://www.wellnessblossom.life/2025/05/anti-aging-skin-treatments.html",
                      "https://www.wellnessblossom.life/2025/05/hormonal-imbalance-supplements-for-women.html",
                      "https://www.wellnessblossom.life/2025/05/why-your-brain-needs-a-digital-detox.html",
                      "https://www.wellnessblossom.life/2025/05/signs-youre-mentally-exhausted.html",
                      "https://www.wellnessblossom.life/2025/05/men-dont-kill-your-fertility.html",
                      "https://www.wellnessblossom.life/2025/05/morning-routines-to-set-up-your-day.html",
                      "https://www.wellnessblossom.life/2025/05/health-benefits-of-onions.html",
                      "https://www.wellnessblossom.life/2025/04/home-remedies-for-headache.html",
                      "https://www.wellnessblossom.life/2025/04/cough-and-flue-natural-remedies.html",
                      "https://www.wellnessblossom.life/2025/04/why-people-get-mood-swings.html",
                      "https://www.wellnessblossom.life/2025/02/sleeping-with-eyes-open.html",
                      "https://www.wellnessblossom.life/2025/02/Synesthesia.html",
                      "https://www.wellnessblossom.life/2025/02/Gut-bacteria-link-to-personality.html",
                      "https://www.wellnessblossom.life/2025/02/longer-and-thicker-hair.html",
                      "https://www.wellnessblossom.life/2025/02/best-natural-antibiotics.html",
                      "https://www.wellnessblossom.life/2025/02/daily-long-life-habits.html",
                      "https://www.wellnessblossom.life/2025/02/cotards-syndrome.html",
                      "https://www.wellnessblossom.life/2025/02/fast-muscle-building.html",
                      "https://www.wellnessblossom.life/2025/02/dangers-of-sleeping-alot.html",
                      "https://www.wellnessblossom.life/2025/02/man-who-lived-without-a-heart.html",
                      "https://www.wellnessblossom.life/2025/02/sweat-and-what-you-eat.html",
                      "https://www.wellnessblossom.life/2025/02/extra-body-parts.html",
                      "https://www.wellnessblossom.life/2025/02/cotards-syndrome.html",
                      "https://www.wellnessblossom.life/2025/02/fast-muscle-building.html",
                      "https://www.wellnessblossom.life/2025/02/dangers-of-sleeping-alot.html",
                      "https://www.wellnessblossom.life/2025/02/man-who-lived-without-a-heart.html",
                      "https://www.wellnessblossom.life/2025/02/sweat-and-what-you-eat.html",
                      "https://www.wellnessblossom.life/2025/02/extra-body-parts.html",
                      "https://www.wellnessblossom.life/2025/02/breathing-wrong.html",
                      "https://www.wellnessblossom.life/2025/02/genetically-modified-foods.html",
                      "https://www.wellnessblossom.life/2025/02/foods-to-boost-your-immune-system.html",
                      "https://www.wellnessblossom.life/2025/01/natural-skin-care-routine.html",
                      "https://www.wellnessblossom.life/2025/01/how-to-stay-active-while-working-desk.html",
                      "https://www.wellnessblossom.life/2025/01/healthy-snacks.html",
                      "https://www.wellnessblossom.life/2025/01/screaming-into-the-void.html",
                      "https://www.wellnessblossom.life/2025/01/sleep-walking.html",
                      "https://www.wellnessblossom.life/2025/01/science-of-laughter.html",
                      "https://www.wellnessblossom.life/2025/01/craving-non-food-items.html",
                      "https://www.wellnessblossom.life/2025/01/physical-mental-health.html"
                      ]

    def get_link(self):
        return random.choice(self.links)
